---
- hosts: hdi
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - name: Umount
    uri:
     url: https://{{ hostvars['hdi']['ansible_host'] }}:9090/mapi/FileSystems/{{ item }}/MountSetting
     method: POST
     return_content: yes
     validate_certs: no
     body: "{{ lookup('template', 'fsumount.j2') }}"
     body_format: raw
     headers:
      Cookie: api-auth={{ hdi_username | b64encode }}:{{ hdi_password | hash('md5') }}
      Content-Type: "application/xml"
    with_items:
    - F1
    - F2
    - F3
    - F4
    - F5
    - F6
    - F7
    - F8
    - F9
    - F10
    - F11
    - F12
    - F13
    - F14
    - F15
    - F16
    - F17
    - F18
    ignore_errors: yes

  - name: Del FS
    uri:
     url: https://{{ hostvars['hdi']['ansible_host'] }}:9090/mapi/FileSystems/{{ item }}
     method: DELETE
     return_content: yes
     validate_certs: no
     body_format: raw
     headers:
      Cookie: api-auth={{ hdi_username | b64encode }}:{{ hdi_password | hash('md5') }}
      Content-Type: "application/xml"
    with_items:
    - F1
    - F2
    - F3
    - F4
    - F5
    - F6
    - F7
    - F8
    - F9
    - F10
    - F11
    - F12
    - F13
    - F14
    - F15
    - F16
    - F17
    - F18
    ignore_errors: yes
