---

- hosts: hdi
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - name: Create HDI File System
    uri:
     url: https://{{hcp_tenant}}.{{hcp_host}}:9090/mapi/tenants/{{ hcp_tenant }}/namespaces
     method: PUT
     return_content: yes
     validate_certs: no
     body: "{{ lookup('template', 'hcp_namespaces.j2') }}"
     body_format: raw
     headers:
      Authorization: HCP {{ hcp_username | b64encode }}:{{ hcp_password | hash('md5') }}
      Content-Type: "application/xml"
