---

- hosts: hdi
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - name: get current time
    shell: date -d '+1 hour' '+%Y-%M-%dT%R:00'
    register: newtime
   
  - debug: 
     msg="{{ newtime.stdout }}"

